[package]
name = "psp-test-app"
version = "0.1.0"
authors = ["Yifeng Wang <doodlewind@gmail.com>"]
edition = "2018"

[dependencies]
psp = "0.1.3"
demolib-sys = { path = "../demolib-sys" }

[build-dependencies]
cc = "1.0"
